class exception3
{
	public static void main(String args[])
	{
		try 
		{

		}
		catch(ArithmeticException e)
		{
			try 
			{

			}
			catch(Exception e1)
			{

			}
			
		}
		
	}
}